### ISSUE TITLE
Run specific dataset in a specific test

### ISSUE THREAD

**Issue by amitbeka** [box/genty#47]
Is there a way to run a specific dataset in a specific test? If not, I think it will be a great addition to the library, which is already great

E.g.
```python

@genty.genty
class Test(unittest.TestCase):
  @genty.genty_dataset(
    hello=('hello', 'Hello'),
    hi_there=('HI THERE', 'Hi There'),
  )
  def test(self, orig, titled):
    self.assertEqual(orig.title(), titled)
```

Then I would like to run only one of the options from outside, something like one of these options:
```
python test.py Test.test.hello
python test.py Test.test hello
python test.py Test.test hi # should run hi_there because of the prefix
python test.py Test hi # should be the same, if possible
```

**Comment by potrebic** [comment]
Thanks for the kind words and your ideas.

I thought a bit about that idea... I believe that logic would be in the test-runner, not genty. Maybe I'm wrong about that? Do you have any thoughts as to how it might be implemented?

You can do something a bit 'hack-isn'. Get to know how gently builds the real/underlying test functions. Here's your example (using nose):

```
$ nosetests test/test_example.py:Test.test\(hello\)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
$ nosetests test/test_example.py:Test.test\(hi_there\)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s
```

genty will build test methods whose **actual** names are
* test(hello)
* test(hi_there)
those are the complete names. Parens included.

If you give your test runner the 'verbose' option it should spit out the full names. For example:

```
$ nosetests test/test_example.py:Test -v
test(hello) (test.test_example.Test) ... ok
test(hi_there) (test.test_example.Test) ... ok
test_other(10) (test.test_example.Test) ... ok
test_other(True) (test.test_example.Test) ... ok
test_other(u'fred') (test.test_example.Test) ... ok

----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
```

Hope that helps!

Be warned... genty could well change how these function names are constructed. The goal is to make them readable in test-runner output above... not make them useable in the manner we're discussing here.

Thanks!

**Comment by amitbeka** [comment]
That does help! thanks. I use unittest, and the same method of giving a complete name with parentheses works for me too. However, running:
```
python test/test_example.py Test.test
```
results in one (random? not sure) test running, except 0 as I had suspected before. This probably means that this feature request should go to the test frameworks themselves :)

Thanks!
